### ISSUE TITLE
Half/Full move clock doesn't decrement

### ISSUE THREAD

**Issue by laurenzlevi** [billforsternz/thc-chess-library#12] opened 2021-08-22 16:17 UTC
Half move clock and full move clock of ChessPositionRaw don't decrement when calling ChessRules::PopMove resulting in possibly false detected draws by 50 move rule

**Comment by billforsternz** [comment] 2021-08-23 06:05
The intended behaviour is that these counters are incremented in PlayMove() as that commits permanently to a move, but not touched in PushMove() / PopMove() which need to be as fast as possible for their purpose of making and undoing position changes for the purpose of move generation only, So this is not a valid issue, in particular the fact that PushMove() doesn't increment implies that PopMove() shouldn't either. Closing Issue.

**Closed by billforsternz** 2021-08-23 06:05 UTC
